### ISSUE TITLE
libpurpletorchat on Windows: Path to tor.exe with vidialia bundle not standard

### ISSUE THREAD

**Issue by geebotron** [prof7bit/TorChat#15]
I know the purple plugin is alpha at the moment, but it would be really useful if it was possible to specify the path to the tor executable in the settings for the plugin.

The "Vidalia bundle" (which I think is a fairly common way to obtain Tor) does not put Tor.exe in \Program Files\Tor\ , but in \Program Files\Vidalia Bundle\Tor\

**Comment by prof7bit** [comment]
Thank you. I will include this in the next version, I already expected something like this would happen but did not yet find the time to investigate all other possible or likely locations for tor.exe. (Pogram files\Tor\ is from the experts bundle (installation without viadalia)). In the next few days (if nothing goes wrong I will have completed file transfer support by this time) there will be a new version of the plugin. Then all features will be implemented, then we can move from alpha to beta and fix all the remaining bugs.

**Comment by prof7bit** [comment]
does it work now? I have included a few more search paths. Ultimately I will also make an option to configure any custom path (and a few more things) but these things will be done when all other problems are solved. Can I close this issue for now?

**Comment by prof7bit** [comment]
I'm closing this issue since it is implemented and no complaints anymore. Please re-open if problem persists.
