### ISSUE TITLE
Bug: Using right click to chat or send file

### ISSUE THREAD

**Issue by AhoyThere** [prof7bit/TorChat#22]
Using TorChat 0.9.9.552 for Windows. Trying to right click someone's name and choose chat or send file doesn't do anything for me. Doubleclicking someone's name or dragging and dropping a file on his name works fine tho. Using right click to chat or send file in version 0.9.9.551 works for me.

I'm not good at bug reporting but I hope this helps.  :)

**Comment by prof7bit** [comment]
you are right. This was intruduced when i merged the pull request regarding the "copy id to clipboard" menu item. I did not test it thoroughly enough after merging this. Fixed in torchat_py branch, will make a new release soon.

**Comment by AhoyThere** [comment]
Great news. Thanks for keeping up your great work. There's a beer incoming.  ;)

**Comment by prof7bit** [comment]
released fixed version in download area: torchat-0.9.9.553
