### ISSUE TITLE
Pidgin TorChat Portable

### ISSUE THREAD

**Issue by yozel** [prof7bit/TorChat#38]
(sorry for my english)

I have many problems with torchat normal. My internet connection crashes when running the torchat. So, I install the pidgin and torchat pidgin plugin and its works. And now, I wanna make a tor+pidgin+torchatplugin bundle without installer. How can i do that ? pidgin torchat plugin connects to tor with C:\Program Files (x86)\Vidalia Bundle\Tor path. But it should connect to tor with CURRENTPATH\Tor path.

Thanks for answers.

**Comment by doll1** [comment]
look for portable pidgin, makes your life easier ;)

Am 09.07.2013 13:10, schrieb yozel:

**Comment by yozel** [comment]
@doll1 Well... how can i add the tor to portable pidgin ? Because  pidgin torchat plugin connects to tor with C:\Program Files (x86)\Vidalia Bundle\Tor

**Comment by doll1** [comment]
Ah, sorry, now I got your problem. Never reviewed the code so I can't 
say if it's hard coded. Imo that should be a config option. But for an 
alpha-release thats excusable. I think ...

Am 10.07.2013 08:13, schrieb yozel:

**Comment by prof7bit** [comment]
You can set an environment variable TOR_EXE that points to the
location of your tor.exe. I did not yet test this extensively but at
least its meant to work this way (I did not do any work on TorChat for
quite some time, I remember wanting to implement a config option for
that but that is not
ready yet but IIRC the environment variable should work already).

**Comment by yozel** [comment]
Thanks for all of comments.
