### ISSUE TITLE
Compilation of torchat2 fail

### ISSUE THREAD

**Issue by ghost** [prof7bit/TorChat#74]
I have downloaded the last revision of torchat2 from git, which is to the last commit a58d1fc on Jan 20, 2014.

I have Free Pascal compiler version 3.0.0, and the compilation fails with the following error:

> make -C src/purple all
> make[1]: Entering directory '/home/rmancuso/Documents/TorChat/src/purple'
> mkdir -p lib
> fpc -Fu../core -Fu../core/lnet-0.6.5 -Fu./libpurple -FU./lib -FE../../bin -g- -CX -Cg -XX -Xs -O3 -k--reduce-memory-overheads -k--no-keep-memory   -dDebugToConsole -dDebugToFile purpletorchat.lpr
> Free Pascal Compiler version 3.0.0 [2016/02/03] for x86_64
> Copyright (c) 1993-2015 by Florian Klaempfl and others
> Target OS: Linux for x86-64
> Compiling purpletorchat.lpr
> purpletorchat.lpr(115,17) Error: Can't determine which overloaded function to call
> purpletorchat.lpr(501,8) Note: User defined: might have sent remove_me in the meantime, write a warning
> purpletorchat.lpr(502,8) Warning: User defined: there are error codes defined for sending IM, use them!
> purpletorchat.lpr(1102,4) Note: User defined: must do something when an IM window is currently open
> purpletorchat.lpr(1246) Fatal: There were 1 errors compiling module, stopping
> Fatal: Compilation aborted
> Error: /usr/bin/ppcx64 returned an error exitcode
> Makefile:22: recipe for target 'all' failed
> make[1]: Leaving directory '/home/rmancuso/Documents/TorChat/src/purple'
> Makefile:12: recipe for target 'purple' failed

**Comment by raffamaiden** [comment]
Here is the patch to make torchat2 compile with fpc 3.0

`diff --git a/src/purple/purpletorchat.lpr b/src/purple/purpletorchat.lpr
index 53444c7..dc61db3 100644
--- a/src/purple/purpletorchat.lpr
+++ b/src/purple/purpletorchat.lpr
@@ -112,7 +112,7 @@ begin
   if Assigned(Buddy) then begin
     Result := Buddy.GetString('buddy_icon');
     if Result <> '' then
-      Result := ConcatPaths([purple_buddy_icons_get_cache_dir(), Result]);
+      Result := ConcatPaths([AnsiString(purple_buddy_icons_get_cache_dir()), AnsiString(Result)]);
   end;
 end;
 `

**Comment by ghost** [comment]
Here is the patch to make torchat2 compile with FPC 3.0

```
diff --git a/src/purple/purpletorchat.lpr b/src/purple/purpletorchat.lpr
index 53444c7..dc61db3 100644
--- a/src/purple/purpletorchat.lpr
+++ b/src/purple/purpletorchat.lpr
@@ -112,7 +112,7 @@ begin
   if Assigned(Buddy) then begin
     Result := Buddy.GetString('buddy_icon');
     if Result <> '' then
-      Result := ConcatPaths([purple_buddy_icons_get_cache_dir(), Result]);
+      Result := ConcatPaths([AnsiString(purple_buddy_icons_get_cache_dir()), AnsiString(Result)]);
   end;
 end;

```

**Comment by gruz** [comment]
The patch helped me at OpenSuse
